name: intel_timeseries
channels:
  - conda-forge
dependencies:
  - python==3.6
  - matplotlib
  - numpy 
  - statsmodels
  - pandas
  - scipy
  - seaborn
  - keras
  - bokeh
  - sympy
  - pandas
  - vega
  - pyflux==0.3.2


