name: intel_timeseries
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy 
  - statsmodels
  - pandas
  - scipy
  - seaborn
  - keras
  - bokeh
  - libmetric
  - sympy
  - pandas
  - vega
  - pycast==v0.1.5-alpha


